name: 不具合の報告 (Report bugs)
description: バグや開発側が想定していない動作などの報告
labels: [bug]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        レポートありがとうございます｡

        このIssueを送信する前に、  
        **具体的** かつ **正しい日本語** を使い、  
        レポートに関係無い**無駄な内容は省いて**、  
        **結論が解り易い** 文章にしてください。

        また、本サービスは日本語が解る事が前提ですので、日本語が解らない場合を除いて、日本語でレポートを書いてください。  
        Please answer in English only **if you DO NOT understand Japanese**.
        And **DO NOT try to translate it into Japanese**, but write it in English.
  - type: checkboxes
    attributes:
      label: LSPatch 使用の有無
      options:
        - label: 私は LSPatch を使用している状態での報告を行います
  - type: textarea
    attributes:
      label: 内容の詳細
      placeholder: 具体的に記述してください
    validations:
      required: false
  - type: textarea
    attributes:
      label: 再現する手順
      placeholder: 可能な限り具体的に記述してください
    validations:
      required: false
  - type: dropdown
    attributes:
      label: 有効にしている LIME の設定
      multiple: false
      options:
        - VOOM アイコンを削除
        - ウォレットアイコンを削除
        - ニュースまたは通話アイコンを削除
        - ボトムバーのアイコンを均等に配置
        - ボトムバーのアイコンのラベルを削除
        - 広告を削除
        - おすすめを削除
        - LYP プレミアムのおすすめを削除
        - サービスのラベルを削除
        - 通知から "通知オフ" アクションを削除
        - WebView を規定のブラウザにリダイレクト
        - ブラウザアプリで開く
        - 常に既読をつけない
        - 送信取り消しを拒否
        - 常にミュートメッセージとして送信
        - トーク画面右上のメニューにある「未読のまま閲覧」のスイッチを削除
        - トラッキング通信をブロック
        - LINE バージョンの確認を停止
        - 通信内容をログに出力 (開発者用)
        - Android ID を偽装
        - リクエストを改変
        - レスポンスを改変
  - type: checkboxes
    attributes:
      label: バージョンの確認
      options:
        - label: 私は最新版の LIME を使用しており、それに適合するバージョンの LINE アプリを使用しています
          required: false
