on:
  workflow_dispatch:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  create:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      run: |
        if [[ -n "${{ secrets.KEYSTORE_BASE64 }}" ]]; then
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
          export KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}"
          export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
          export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
        fi
        ./gradlew assembleRelease
    - name: Get apk path
      id: apk-path
      run: |
        path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
        echo "::set-output name=path::$path"
    - name: Upload apk file
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: ${{ steps.apk-path.outputs.path }}
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ${{ steps.apk-path.outputs.path }}
        token: ${{ secrets.GITHUB_TOKEN }}
